# Generated by Django 4.2.11 on 2024-04-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
