# Generated by Django 4.2.11 on 2024-04-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
